/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'media-assets': MediaAsset;
    pages: Page;
    expertises: Expertise;
    projects: Project;
    realisations: Realisation;
    formations: Formation;
    'formation-sessions': FormationSession;
    events: Event;
    products: Product;
    'team-members': TeamMember;
    partners: Partner;
    testimonials: Testimonial;
    'legal-documents': LegalDocument;
    'contact-messages': ContactMessage;
    redirects: Redirect;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'media-assets': MediaAssetsSelect<false> | MediaAssetsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    expertises: ExpertisesSelect<false> | ExpertisesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    realisations: RealisationsSelect<false> | RealisationsSelect<true>;
    formations: FormationsSelect<false> | FormationsSelect<true>;
    'formation-sessions': FormationSessionsSelect<false> | FormationSessionsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'ceo-message': CeoMessage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'ceo-message': CeoMessageSelect<false> | CeoMessageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Administrator: full access. Publisher: publishes content. Editor: drafts only.
   */
  role: 'administrator' | 'publisher' | 'editor';
  /**
   * Unchecking suspends access immediately, without deleting the content produced.
   */
  isActive?: boolean | null;
  /**
   * Checked on creation. Cleared automatically as soon as the user changes their password.
   */
  mustChangePassword?: boolean | null;
  locale?: ('fr' | 'en') | null;
  lastLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets".
 */
export interface MediaAsset {
  id: number;
  /**
   * Describes what the image or video shows, for accessibility and search engines. Required.
   */
  altFr: string;
  /**
   * Required to guarantee accessibility and SEO on the English version.
   */
  altEn: string;
  caption?: string | null;
  /**
   * Author, licence, or “demo visual”. Checked before going live.
   */
  rightsNote?: string | null;
  /**
   * Set by the seed script. Do not edit: it is what prevents duplicates.
   */
  demoKey?: string | null;
  /**
   * Must be replaced by a real visual before going live.
   */
  isDemo?: boolean | null;
  /**
   * Allows anonymous access to the file. Keep disabled for internal or pending files.
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Determines which section of the site this header applies to.
   */
  pageKey:
    | 'expertises'
    | 'realisations'
    | 'projets'
    | 'formations-evenements'
    | 'evenements'
    | 'produits'
    | 'a-propos'
    | 'contact';
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  /**
   * The small text above the title.
   */
  eyebrow: string;
  title: string;
  intro?: string | null;
  /**
   * Shown while no content is published in this section.
   */
  emptyStateTitle?: string | null;
  emptyStateText?: string | null;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertises".
 */
export interface Expertise {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Picked from the design system icon set.
   */
  iconKey?: ('wrench' | 'install' | 'grad' | 'box' | 'weld' | 'bolt' | 'target' | 'globe' | 'layers') | null;
  position?: number | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  /**
   * Shown on the domain card.
   */
  summary: string;
  body: string;
  /**
   * What the domain covers in detail. Shown as cards under the description.
   */
  servicePoints?:
    | {
        label: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main image shown on the domain card and page. FR and EN alternative text are managed in the media library.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Project progress  -  unrelated to the publication status.
   */
  projectState: 'planned' | 'ongoing' | 'done';
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  summary: string;
  body: string;
  clientName?: string | null;
  country?: string | null;
  startDate?: string | null;
  /**
   * Advanced option kept for existing entries and public links.
   */
  expertise?: (number | null) | Expertise;
  /**
   * Choose an existing media item or click “Add media”. French and English alt text are required.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realisations".
 */
export interface Realisation {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  isFeatured?: boolean | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  /**
   * Two or three sentences. This is what is read on the card, before opening the entry.
   */
  summary: string;
  /**
   * The client’s problem before the work.
   */
  context: string;
  /**
   * What was actually done.
   */
  solution: string;
  /**
   * What changed, measured where possible. This is the proof.
   */
  results: string;
  clientName?: string | null;
  year?: number | null;
  sector?: string | null;
  country?: string | null;
  /**
   * Kept for existing entries and public links; optional.
   */
  expertise?: (number | null) | Expertise;
  /**
   * Advanced option kept for existing entries. The written results are enough to publish a new case study.
   */
  metrics?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used on the card and at the top of the entry. Falls back to the “after” visual.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Optional. Fill only when a before/after comparison adds useful evidence.
   */
  beforeMedia?: (number | null) | MediaAsset;
  /**
   * Optional. Used as a fallback when no main visual is provided.
   */
  afterMedia?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations".
 */
export interface Formation {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  theme: 'maintenance' | 'securite' | 'leadership' | 'innovation';
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  /**
   * What the course enables, in one sentence.
   */
  summary: string;
  /**
   * Who it is for. Prevents off-target enrolment.
   */
  audience: string;
  /**
   * For example “21 h  -  3 days”.
   */
  duration: string;
  /**
   * For example “On site”, “Hybrid”.
   */
  format: string;
  /**
   * One objective per line, phrased as an action.
   */
  objectives?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  prerequisites?: string | null;
  /**
   * Main course image. FR and EN alternative text are managed in the media library.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation-sessions".
 */
export interface FormationSession {
  id: number;
  label?: string | null;
  formation: number | Formation;
  startsAt: string;
  endsAt?: string | null;
  locationName: string;
  city: string;
  country: string;
  /**
   * Kept for existing data; the site handles no registration or payment.
   */
  seats?: number | null;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  /**
   * Workshop, meetup, conference…
   */
  eventType: string;
  summary: string;
  /**
   * The schedule. The site handles no registration or ticketing.
   */
  body: string;
  startsAt: string;
  /**
   * Without an end date, a one-day event stays listed as upcoming until the next day.
   */
  endsAt?: string | null;
  locationName: string;
  city: string;
  country: string;
  /**
   * Main event image. FR and EN alternative text are managed in the media library.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Unique. Used to identify the product in a quotation.
   */
  reference: string;
  /**
   * Optional. Leave empty when the product is quoted individually or the price is confidential.
   */
  unitPrice?: number | null;
  isFeatured?: boolean | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  /**
   * Feeds the catalogue filter. Reuse existing categories rather than inventing new ones.
   */
  category: string;
  /**
   * One or two sentences, read on the card.
   */
  summary: string;
  description: string;
  /**
   * For example “On quotation”, “To order”.
   */
  availability: string;
  leadTime?: string | null;
  /**
   * Label / value pairs, never free text: this is what makes one entry comparable to another.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The button always leads to the Contact page. Leave empty to hide it.
   */
  ctaLabel?: string | null;
  /**
   * Main image for the product card and detail page. Use media with both FR and EN alternative text.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Optional. Add a technical PDF that visitors can download from the product page.
   */
  productSheet?: (number | null) | MediaAsset;
  /**
   * Optional. Upload an MP4, WebM or OGG video. It takes priority over the YouTube link.
   */
  videoMedia?: (number | null) | MediaAsset;
  /**
   * Optional. Paste a youtube.com/watch?v=… or youtu.be/… URL.
   */
  videoUrl?: string | null;
  /**
   * Optional. Add photos in the desired rotation order. They are presented in a scrollable gallery.
   */
  gallery360?:
    | {
        image: number | MediaAsset;
        id?: string | null;
      }[]
    | null;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  position?: number | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  name: string;
  role: string;
  bio: string;
  /**
   * Optional. Left empty, the icon is hidden.
   */
  linkedinUrl?: string | null;
  /**
   * Choose an existing media item or add a portrait from the media library. French and English alt text are required.
   */
  portrait?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  position?: number | null;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  name: string;
  /**
   * Optional for international brands. Fill this in when the French name is a description that needs translating.
   */
  nameEn?: string | null;
  /**
   * Optional. Left empty, the logo is shown without a link  -  never a dead link.
   */
  externalUrl?: string | null;
  /**
   * Click “Choose existing”, then “Add media” to upload the logo. JPEG, PNG, WebP or AVIF, with French and English alt text.
   */
  logo?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Lowercase, no accents or spaces. Changing it creates a 301 redirect from the former address.
   */
  slug: string;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  /**
   * Date of the quoted person’s written agreement. Required: publishing someone’s words without evidence of consent is a breach, not a detail.
   */
  consentReceivedAt: string;
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  /**
   * Publishing requires both a French and an English quote. Save the draft, then complete the English locale before choosing “Published”.
   */
  quote: string;
  personName: string;
  role?: string | null;
  company?: string | null;
  /**
   * Optional. Fill this in when the company name is descriptive and needs translating.
   */
  companyEn?: string | null;
  /**
   * Optional. Choose an existing media item or add the portrait from the media library. French and English alt text are required.
   */
  portrait?: (number | null) | MediaAsset;
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  /**
   * Draft → In review → Published. An Editor cannot go beyond “In review”.
   */
  editorialStatus: 'draft' | 'review' | 'published' | 'archived';
  /**
   * Required to archive. The reason is kept in the audit log.
   */
  archiveReason?: string | null;
  documentKey: 'legal_notice' | 'privacy_policy';
  /**
   * Comes from the demo data set. Replace with real content before going live.
   */
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  publishedAt?: string | null;
  title: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Unique to this page and to each language. Generic values are rejected.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Used by social networks. Falls back to the main visual.
     */
    ogImage?: (number | null) | MediaAsset;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  subject?: string | null;
  fullName: string;
  email: string;
  /**
   * Optional. Used only to follow up on this request.
   */
  phone?: string | null;
  company?: string | null;
  need: string;
  message: string;
  consentAt: string;
  state?: ('new' | 'in_progress' | 'replied' | 'closed' | 'redacted') | null;
  assignedTo?: (number | null) | User;
  ipHash?: string | null;
  userAgentHash?: string | null;
  /**
   * Past this date the message is anonymised by the cleanup task (prompt 08).
   */
  retentionUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  statusCode?: ('301' | '308') | null;
  reason?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only log  -  not editable, not even by an administrator.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  summary?: string | null;
  action:
    | 'create'
    | 'update'
    | 'publish'
    | 'unpublish'
    | 'archive'
    | 'delete'
    | 'login'
    | 'logout'
    | 'settings_change'
    | 'read'
    | 'export'
    | 'preview'
    | 'login_failed'
    | 'access_denied'
    | 'purge'
    | 'security';
  entityType: string;
  entityId?: string | null;
  actor?: (number | null) | User;
  note?: string | null;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  method?: string | null;
  path?: string | null;
  statusCode?: number | null;
  result?: string | null;
  /**
   * Non-reversible hash. The plain address is never stored.
   */
  ipHash?: string | null;
  userAgentHash?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media-assets';
        value: number | MediaAsset;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'expertises';
        value: number | Expertise;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'realisations';
        value: number | Realisation;
      } | null)
    | ({
        relationTo: 'formations';
        value: number | Formation;
      } | null)
    | ({
        relationTo: 'formation-sessions';
        value: number | FormationSession;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  isActive?: T;
  mustChangePassword?: T;
  locale?: T;
  lastLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-assets_select".
 */
export interface MediaAssetsSelect<T extends boolean = true> {
  altFr?: T;
  altEn?: T;
  caption?: T;
  rightsNote?: T;
  demoKey?: T;
  isDemo?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  editorialStatus?: T;
  archiveReason?: T;
  pageKey?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  eyebrow?: T;
  title?: T;
  intro?: T;
  emptyStateTitle?: T;
  emptyStateText?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertises_select".
 */
export interface ExpertisesSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  iconKey?: T;
  position?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  body?: T;
  servicePoints?:
    | T
    | {
        label?: T;
        text?: T;
        id?: T;
      };
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  projectState?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  body?: T;
  clientName?: T;
  country?: T;
  startDate?: T;
  expertise?: T;
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realisations_select".
 */
export interface RealisationsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  isFeatured?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  context?: T;
  solution?: T;
  results?: T;
  clientName?: T;
  year?: T;
  sector?: T;
  country?: T;
  expertise?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  media?: T;
  beforeMedia?: T;
  afterMedia?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations_select".
 */
export interface FormationsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  theme?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  summary?: T;
  audience?: T;
  duration?: T;
  format?: T;
  objectives?:
    | T
    | {
        text?: T;
        id?: T;
      };
  prerequisites?: T;
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formation-sessions_select".
 */
export interface FormationSessionsSelect<T extends boolean = true> {
  label?: T;
  formation?: T;
  startsAt?: T;
  endsAt?: T;
  locationName?: T;
  city?: T;
  country?: T;
  seats?: T;
  editorialStatus?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  eventType?: T;
  summary?: T;
  body?: T;
  startsAt?: T;
  endsAt?: T;
  locationName?: T;
  city?: T;
  country?: T;
  media?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  reference?: T;
  unitPrice?: T;
  isFeatured?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  category?: T;
  summary?: T;
  description?: T;
  availability?: T;
  leadTime?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  ctaLabel?: T;
  media?: T;
  productSheet?: T;
  videoMedia?: T;
  videoUrl?: T;
  gallery360?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  position?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  name?: T;
  role?: T;
  bio?: T;
  linkedinUrl?: T;
  portrait?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  position?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  name?: T;
  nameEn?: T;
  externalUrl?: T;
  logo?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  slug?: T;
  editorialStatus?: T;
  archiveReason?: T;
  consentReceivedAt?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  quote?: T;
  personName?: T;
  role?: T;
  company?: T;
  companyEn?: T;
  portrait?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  editorialStatus?: T;
  archiveReason?: T;
  documentKey?: T;
  isDemo?: T;
  createdBy?: T;
  updatedBy?: T;
  publishedAt?: T;
  title?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  subject?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  company?: T;
  need?: T;
  message?: T;
  consentAt?: T;
  state?: T;
  assignedTo?: T;
  ipHash?: T;
  userAgentHash?: T;
  retentionUntil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  statusCode?: T;
  reason?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  summary?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  actor?: T;
  note?: T;
  before?: T;
  after?: T;
  requestId?: T;
  method?: T;
  path?: T;
  statusCode?: T;
  result?: T;
  ipHash?: T;
  userAgentHash?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  baseline: string;
  /**
   * Choose the logo from the media library or click “Add media”. Provide French and English alt text.
   */
  logo?: (number | null) | MediaAsset;
  /**
   * Browser icon. Choose a square media item from the library or add a new one.
   */
  favicon?: (number | null) | MediaAsset;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * Example: 6.3703. The map is shown when latitude and longitude are provided.
   */
  mapLatitude?: number | null;
  /**
   * Example: 2.3912.
   */
  mapLongitude?: number | null;
  mapZoom?: number | null;
  phone?: string | null;
  /**
   * Digits and + only.
   */
  phoneRaw?: string | null;
  /**
   * International format recommended: +229 01 42 54 54 95. Spaces and punctuation are normalized for wa.me.
   */
  whatsapp?: string | null;
  email?: string | null;
  openingHours?:
    | {
        days: string;
        hours: string;
        id?: string | null;
      }[]
    | null;
  replyDelay?: string | null;
  /**
   * An entry without a URL is not displayed: never a dead link.
   */
  socialLinks?:
    | {
        network: 'li' | 'fb' | 'yt';
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * French is the default language and cannot be disabled.
   */
  englishEnabled?: boolean | null;
  cookieTitle: string;
  cookieText: string;
  /**
   * Used for the homepage and as a suffix. It never replaces a page’s own SEO.
   */
  defaultSeoTitle: string;
  defaultSeoDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Add an entry, choose its destination, fill in its label in both languages, then enable Visible. The change appears in the header and footer after saving.
   */
  mainMenu?:
    | {
        label: string;
        section:
          | 'home'
          | 'expertises'
          | 'realisations'
          | 'projets'
          | 'formationsEvenements'
          | 'evenements'
          | 'produits'
          | 'aPropos'
          | 'contact';
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  /**
   * Button shown in the footer. Clear the field to remove it from the site. A testimonial sent by a client is never published automatically: it lands in Contact messages and you decide whether to publish it from Testimonials.
   */
  testimonialLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  /**
   * Rendered in serif italic inside the title, as in the approved mockup.
   */
  heroHighlight?: string | null;
  heroLead?: string | null;
  /**
   * Choose an existing media item or click “Add media”. French and English alt text are required.
   */
  heroMedia?: (number | null) | MediaAsset;
  /**
   * Add up to three visuals. They rotate automatically every 4 seconds. The first visual is used when the carousel is empty.
   */
  heroMediaCarousel?:
    | {
        media: number | MediaAsset;
        id?: string | null;
      }[]
    | null;
  /**
   * Order and visibility of homepage blocks. A hidden section is not rendered.
   */
  sections?:
    | {
        key:
          | 'trust'
          | 'about'
          | 'expertises'
          | 'products'
          | 'figures'
          | 'realisations'
          | 'trainingEvents'
          | 'leadership'
          | 'testimonials'
          | 'cta';
        eyebrow?: string | null;
        title?: string | null;
        intro?: string | null;
        ctaLabel?: string | null;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Dedicated section for homepage statistics. Fill in both languages and use “Visible” to publish or remove each figure.
   */
  keyFigures?:
    | {
        /**
         * Number displayed on the homepage. Leave empty to hide the metric.
         */
        value?: number | null;
        suffix?: string | null;
        label: string;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  featuredProducts?: (number | Product)[] | null;
  featuredRealisations?: (number | Realisation)[] | null;
  featuredFormations?: (number | Formation)[] | null;
  featuredEvents?: (number | Event)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ceo-message".
 */
export interface CeoMessage {
  id: number;
  personName: string;
  personRole: string;
  messageTitle: string;
  lead: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Choose an existing media item or add the portrait from the media library.
   */
  portrait?: (number | null) | MediaAsset;
  /**
   * https:// URL of a hosted video. Loaded only after cookie consent.
   */
  videoUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  presentation: string;
  vision: string;
  pillars?:
    | {
        icon?: ('target' | 'globe' | 'layers' | 'shield' | 'grad' | 'bolt') | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Choose an existing media item or click “Add media”. French and English alt text are required.
   */
  media?: (number | null) | MediaAsset;
  /**
   * Optional. An MP4, WebM or OGG video replaces the visual on the homepage. Add a YouTube URL as a fallback if needed.
   */
  videoMedia?: (number | null) | MediaAsset;
  /**
   * Optional. Paste a youtube.com/watch?v=… or youtu.be/… URL. The uploaded video takes priority.
   */
  videoUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  baseline?: T;
  logo?: T;
  favicon?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  country?: T;
  mapLatitude?: T;
  mapLongitude?: T;
  mapZoom?: T;
  phone?: T;
  phoneRaw?: T;
  whatsapp?: T;
  email?: T;
  openingHours?:
    | T
    | {
        days?: T;
        hours?: T;
        id?: T;
      };
  replyDelay?: T;
  socialLinks?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  englishEnabled?: T;
  cookieTitle?: T;
  cookieText?: T;
  defaultSeoTitle?: T;
  defaultSeoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        section?: T;
        isVisible?: T;
        id?: T;
      };
  contactLabel?: T;
  testimonialLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroHighlight?: T;
  heroLead?: T;
  heroMedia?: T;
  heroMediaCarousel?:
    | T
    | {
        media?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        key?: T;
        eyebrow?: T;
        title?: T;
        intro?: T;
        ctaLabel?: T;
        isVisible?: T;
        id?: T;
      };
  keyFigures?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        isVisible?: T;
        id?: T;
      };
  featuredProducts?: T;
  featuredRealisations?: T;
  featuredFormations?: T;
  featuredEvents?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ceo-message_select".
 */
export interface CeoMessageSelect<T extends boolean = true> {
  personName?: T;
  personRole?: T;
  messageTitle?: T;
  lead?: T;
  body?: T;
  portrait?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  presentation?: T;
  vision?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  media?: T;
  videoMedia?: T;
  videoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}